### ISSUE TITLE
Tensor are not uploaded when creating a dataset

### ISSUE THREAD

**Issue by tcp** [OpenMined/pygrid-admin#73]
## Description
It's not possible to ship tensors with datasets.

## How to Reproduce
1. Create a new dataset
2. Add a tensor
3. Submit
4. Tensor is not sent to PyGrid

## Expected Behavior
It should be possible to send _multiple_ tensors when creating a dataset.

## Additional Context
It's a good opportunity to handle this in #66. Whichever comes first, this needs to be fixed.

**Comment by victorperezc** [comment]
This Issue seems to be related to PyGrid itself. Below the stack trace

```
Traceback (most recent call last):
  File "/Users/victor/Desktop/openmined/PyGrid/apps/domain/env/lib/python3.9/site-packages/gevent/pywsgi.py", line 1077, in handle_one_response
    self.run_application()
  File "/Users/victor/Desktop/openmined/PyGrid/apps/domain/env/lib/python3.9/site-packages/geventwebsocket/handler.py", line 86, in run_application
    return super(WebSocketHandler, self).run_application()
  File "/Users/victor/Desktop/openmined/PyGrid/apps/domain/env/lib/python3.9/site-packages/gevent/pywsgi.py", line 1023, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/Users/victor/Desktop/openmined/PyGrid/apps/domain/env/lib/python3.9/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/victor/Desktop/openmined/PyGrid/apps/domain/env/lib/python3.9/site-packages/flask_sockets.py", line 47, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/victor/Desktop/openmined/PyGrid/apps/domain/env/lib/python3.9/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/victor/Desktop/openmined/PyGrid/apps/domain/env/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/victor/Desktop/openmined/PyGrid/apps/domain/env/lib/python3.9/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/victor/Desktop/openmined/PyGrid/apps/domain/env/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/victor/Desktop/openmined/PyGrid/apps/domain/env/lib/python3.9/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/victor/Desktop/openmined/PyGrid/apps/domain/env/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/victor/Desktop/openmined/PyGrid/apps/domain/env/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/victor/Desktop/openmined/PyGrid/apps/domain/env/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/victor/Desktop/openmined/PyGrid/apps/domain/env/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/victor/Desktop/openmined/PyGrid/apps/domain/env/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/victor/Desktop/openmined/PyGrid/apps/domain/env/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/victor/Desktop/openmined/PyGrid/apps/domain/src/main/routes/auth.py", line 51, in wrapper
    return f(current_user, *args, **kwargs)
  File "/Users/victor/Desktop/openmined/PyGrid/apps/domain/src/main/routes/data_centric/datasets/routes.py", line 26, in create_dataset
    dataset = loads(dataset)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-04-14T14:08:16Z {'REMOTE_ADDR': '127.0.0.1', 'REMOTE_PORT': '53869', 'HTTP_HOST': 'localhost:5000', (hidden keys: 28)} failed with JSONDecodeError

```

**Comment by victorperezc** [comment]
PyGrid hasn't yet implemented functionality to process files such as csv or images and can only accept tensors encoded in json formats. Either we implement the file functionality on PyGrid side or refactor PyGrid admin to work with PyGrid as of now.
